/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.quartzwater.medicalglossary;

import backend.TermDataManagement;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author BRIN
 */
public class HyperlinkShowWindow extends javax.swing.JFrame {

    private TermDataManagement tdm;
    private String inputTerm;
    private boolean isEditModeEnabled;
    private boolean initialisedVIACreate;
    
    /**
     * Creates new form HyperlinkEditWindow
     */
    
    

    public HyperlinkShowWindow(TermDataManagement tdm, String inputTerm, boolean isEditModeEnabled, boolean initialisedVIACreate) {
        initComponents();
        this.tdm = tdm;
        this.inputTerm = inputTerm;
        this.isEditModeEnabled = isEditModeEnabled;
        this.initialisedVIACreate = initialisedVIACreate;
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusLabel1 = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        statusLabel3 = new javax.swing.JLabel();
        statusLabel4 = new javax.swing.JLabel();
        statusLabel5 = new javax.swing.JLabel();
        statusLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(670, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.setPreferredSize(new java.awt.Dimension(190, 400));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(58, 63, 66));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("2");
        jLabel13.setOpaque(true);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 40, 40));

        jLabel14.setBackground(new java.awt.Color(58, 63, 66));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("3");
        jLabel14.setOpaque(true);
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        jLabel15.setBackground(new java.awt.Color(58, 63, 66));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("4");
        jLabel15.setOpaque(true);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 40));

        jLabel16.setBackground(new java.awt.Color(58, 63, 66));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("5");
        jLabel16.setOpaque(true);
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, 40));

        jLabel7.setBackground(new java.awt.Color(58, 63, 66));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, 40));

        jLabel12.setBackground(new java.awt.Color(58, 63, 66));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("1");
        jLabel12.setOpaque(true);
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 40));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 190, 400));

        jPanel4.setBackground(new java.awt.Color(34, 40, 44));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(34, 40, 44));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Hyperlink");
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        statusLabel.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel.setText("Status:");
        statusLabel.setOpaque(true);
        jPanel4.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 520, 40));

        statusLabel1.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        statusLabel1.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel1.setText("Status:");
        statusLabel1.setOpaque(true);
        jPanel4.add(statusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 520, -1));

        statusLabel2.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel2.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel2.setText("Status:");
        statusLabel2.setOpaque(true);
        jPanel4.add(statusLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, 40));

        statusLabel3.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel3.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel3.setText("Status:");
        statusLabel3.setOpaque(true);
        jPanel4.add(statusLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 520, 40));

        statusLabel4.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel4.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel4.setText("Status:");
        statusLabel4.setOpaque(true);
        jPanel4.add(statusLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 520, 40));

        statusLabel5.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel5.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel5.setText("Status:");
        statusLabel5.setOpaque(true);
        jPanel4.add(statusLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 520, 40));

        statusLabel6.setBackground(new java.awt.Color(34, 40, 44));
        statusLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        statusLabel6.setForeground(new java.awt.Color(204, 204, 204));
        statusLabel6.setText("Status:");
        statusLabel6.setOpaque(true);
        jPanel4.add(statusLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 520, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 560, 400));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HyperlinkShowWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HyperlinkShowWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HyperlinkShowWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HyperlinkShowWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HyperlinkShowWindow(null, null, false, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JLabel statusLabel2;
    private javax.swing.JLabel statusLabel3;
    private javax.swing.JLabel statusLabel4;
    private javax.swing.JLabel statusLabel5;
    private javax.swing.JLabel statusLabel6;
    // End of variables declaration//GEN-END:variables
}
