/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import book.bookpicker.Book;
import book.bookpicker.bookConstructor;
import com.quartzwater.medicalglossary.AfterEventCode;
import com.quartzwater.medicalglossary.BehaviourForSwing;
import java.awt.Color;
import java.util.List;
import java.util.Map;

/**
 *
 * @author BRIN
 */
public class bookPickerFrame extends javax.swing.JFrame {

    /**
     * Creates new form bookPickerFrame
     */
    
    private Color activeColor = new Color(27,36,45);
    
    private int currentYear = 1;
    
    private RoundedButton[] selectionButtonArray;
    
    
    
    private void initializeSelectionButtons(){
        
        for(int i = 0; i < selectionButtonArray.length; i++){
            
            BehaviourForSwing.removeRoundedButtonActionBehaviour(selectionButtonArray[i]);
        }
        
        List<Book> bookList = bookConstructor.getBooksByYear(currentYear);
        int size = bookList.size();
        
        for(int index = 0; index < Math.min(size, 6); index++){
            
            selectionButtonArray[index].setText(bookList.get(index).getShortHandTitle());
            BehaviourForSwing.addSpecificRoundedButtonActionBehaviour(
                    selectionButtonArray[index], 
                    bookList.get(index).getColorScheme(), 
                    bookList.get(index).getActionCode()
            );
            
            System.out.println("loop ran");
        }
        
        
    }
    
    
    
    public bookPickerFrame() {
        initComponents();
        selectionButtonArray = new RoundedButton[]{
        
        selectionButton1,
        selectionButton2,
        selectionButton3,
        selectionButton4,
        selectionButton5,
        selectionButton6
    };
        initializeSelectionButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        selectionButton3 = new frontend.RoundedButton();
        selectionButton1 = new frontend.RoundedButton();
        selectionButton2 = new frontend.RoundedButton();
        selectionButton6 = new frontend.RoundedButton();
        selectionButton4 = new frontend.RoundedButton();
        selectionButton5 = new frontend.RoundedButton();
        rightRotateLabel = new javax.swing.JLabel();
        ordinalIndicatorLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        ordinalNumberLabel = new javax.swing.JLabel();
        leftRotateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Pick A Book");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 280, -1));

        selectionButton3.setText("-");
        selectionButton3.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 80));

        selectionButton1.setText("-");
        selectionButton1.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 80));

        selectionButton2.setText("-");
        selectionButton2.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 80));

        selectionButton6.setText("-");
        selectionButton6.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, 80));

        selectionButton4.setText("-");
        selectionButton4.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 80));

        selectionButton5.setText("-");
        selectionButton5.setDefaultColor(new java.awt.Color(57, 75, 92));
        selectionButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 80));

        rightRotateLabel.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 60)); // NOI18N
        rightRotateLabel.setForeground(new java.awt.Color(255, 255, 255));
        rightRotateLabel.setText(">");
        rightRotateLabel.setToolTipText("");
        jPanel1.add(rightRotateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, 80));

        ordinalIndicatorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ordinalIndicatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordinalIndicatorLabel.setText("st");
        jPanel1.add(ordinalIndicatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 120, 50, -1));

        yearLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("YEAR");
        jPanel1.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 149, -1, 30));

        ordinalNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        ordinalNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordinalNumberLabel.setText("1");
        ordinalNumberLabel.setToolTipText("");
        jPanel1.add(ordinalNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        leftRotateLabel.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 60)); // NOI18N
        leftRotateLabel.setForeground(new java.awt.Color(255, 255, 255));
        leftRotateLabel.setText("<");
        leftRotateLabel.setToolTipText("");
        jPanel1.add(leftRotateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookPickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookPickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookPickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookPickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookPickerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftRotateLabel;
    private javax.swing.JLabel ordinalIndicatorLabel;
    private javax.swing.JLabel ordinalNumberLabel;
    private javax.swing.JLabel rightRotateLabel;
    private frontend.RoundedButton selectionButton1;
    private frontend.RoundedButton selectionButton2;
    private frontend.RoundedButton selectionButton3;
    private frontend.RoundedButton selectionButton4;
    private frontend.RoundedButton selectionButton5;
    private frontend.RoundedButton selectionButton6;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables


    
}
