/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AppConfig;
import backend.AppConstants;
import book.HarpersIllustratedBiochemistry.Content;
import book.bookpicker.Book;
import book.bookpicker.BookConstructor;
import legacy.AfterEventCode;
import legacy.BehaviourForSwing;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author BRIN
 */
public class bookPickerFrame extends javax.swing.JFrame {

    /**
     * Creates new form bookPickerFrame
     */
    
    private Color activeColor = new Color(27,36,45);
    
    private int currentYear = 1;
    
    private RoundedButton[] selectionButtonArray;
    
    // LEGACY
    /*
    
    private void initializeSelectionButtons(){
        
        for(int i = 0; i < selectionButtonArray.length; i++){
            
            BehaviourForSwing.removeRoundedButtonActionBehaviour(selectionButtonArray[i]);
        }
        
        List<Book> bookList = BookConstructor.getBooksByYear(currentYear);
        int size = bookList.size();
        
        for(int index = 0; index < Math.min(size, 6); index++){
            
            selectionButtonArray[index].setText(bookList.get(index).getShortHandTitle());
            BehaviourForSwing.addSpecificRoundedButtonActionBehaviour(
                    selectionButtonArray[index], 
                    bookList.get(index).getColorScheme(), 
                    bookList.get(index).getActionCode()
            );
            
            System.out.println("loop ran");
        }
        
        
    }
    
    */
    
    private bookPickerFrame() {
        initComponents();
        selectionButtonArray = new RoundedButton[]{
        
        selectionButton1,
        selectionButton2,
        selectionButton3,
        selectionButton4,
        selectionButton5,
        selectionButton6
    };
        
        // LEGACY :: initializeSelectionButtons();
    }
    
    public static bookPickerFrame generateInstance(){
        
        bookPickerFrame bpf = new bookPickerFrame();
        bookPickerController.initializeController(bpf);
        return bpf;
    }
    
    public static bookPickerFrame generateInstanceWithoutController(){
     
        bookPickerFrame bpf = new bookPickerFrame();
        return bpf;
    }
    
    
    protected RoundedButton[] getSelectionButtonArray(){
        
        return selectionButtonArray;
    }
    
    protected JLabel getLeftRotateLabel(){
        
        return leftRotateLabel;
    }
    
    protected JLabel getRightRotateLabel(){
        
        return rightRotateLabel;
    }
    
    protected JLabel getOrdinalNumberLabel(){
        
        return ordinalNumberLabel;
    }
    
    protected JLabel getOrdinalIndicatorLabel(){
        
        return ordinalIndicatorLabel;
    }
    
    protected JLabel getYearLabel(){
        
        return yearLabel;
    }
    
    protected RoundedButton getSettingsButton(){
        
        return settingsButton;
    }
    
    protected SVGIconPanel getSettingsIconPanel(){
        
        return settingsIconPanel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        selectionButton3 = new frontend.RoundedButton();
        selectionButton1 = new frontend.RoundedButton();
        selectionButton2 = new frontend.RoundedButton();
        selectionButton6 = new frontend.RoundedButton();
        selectionButton4 = new frontend.RoundedButton();
        selectionButton5 = new frontend.RoundedButton();
        rightRotateLabel = new javax.swing.JLabel();
        ordinalIndicatorLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        ordinalNumberLabel = new javax.swing.JLabel();
        leftRotateLabel = new javax.swing.JLabel();
        settingsIconPanel = new frontend.SVGIconPanel();
        settingsButton = new frontend.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medical Glossary - Choose A Book");
        setMinimumSize(new java.awt.Dimension(800, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Choose A Book");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 280, -1));

        selectionButton3.setText("-");
        selectionButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 80));

        selectionButton1.setText("-");
        selectionButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 80));

        selectionButton2.setText("-");
        selectionButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 80));

        selectionButton6.setText("-");
        selectionButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, 80));

        selectionButton4.setText("-");
        selectionButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 80));

        selectionButton5.setText("-");
        selectionButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(selectionButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 80));

        rightRotateLabel.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 60)); // NOI18N
        rightRotateLabel.setForeground(new java.awt.Color(255, 255, 255));
        rightRotateLabel.setText(">");
        rightRotateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(rightRotateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, 80));

        ordinalIndicatorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ordinalIndicatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordinalIndicatorLabel.setText("st");
        jPanel1.add(ordinalIndicatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 120, 50, -1));

        yearLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("YEAR");
        jPanel1.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 149, -1, 30));

        ordinalNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        ordinalNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordinalNumberLabel.setText("1");
        ordinalNumberLabel.setToolTipText("");
        jPanel1.add(ordinalNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        leftRotateLabel.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 60)); // NOI18N
        leftRotateLabel.setForeground(new java.awt.Color(255, 255, 255));
        leftRotateLabel.setText("<");
        leftRotateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(leftRotateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 80));

        try {
            settingsIconPanel.set_SVG_URL_String("/images/icons/settings.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        settingsIconPanel.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        settingsIconPanel.setIconSquarePadding(7.0);
        jPanel1.add(settingsIconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 30, 30));

        settingsButton.setText("Settings");
        settingsButton.setArcSize(15);
        settingsButton.setCurrentColor(new java.awt.Color(44, 62, 80));
        settingsButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        settingsButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftRotateLabel;
    private javax.swing.JLabel ordinalIndicatorLabel;
    private javax.swing.JLabel ordinalNumberLabel;
    private javax.swing.JLabel rightRotateLabel;
    private frontend.RoundedButton selectionButton1;
    private frontend.RoundedButton selectionButton2;
    private frontend.RoundedButton selectionButton3;
    private frontend.RoundedButton selectionButton4;
    private frontend.RoundedButton selectionButton5;
    private frontend.RoundedButton selectionButton6;
    private frontend.RoundedButton settingsButton;
    private frontend.SVGIconPanel settingsIconPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables


    
}
