/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.*;
import javax.swing.JLabel;

/**
 *
 * @author BRIN
 */
public class hyperlinkViewFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form hyperlinkViewFrame
     */
    private hyperlinkViewFrame(SourceFrame sf, Term existingTerm) {
        initComponents();
        this.setTitle("Viewing hyperlinks for : '" + existingTerm.getAbsoluteSpelling()+ "'");
    }
    
    
    
    
    protected SVGIconPanel[] getSVGIcons(){
        
        return new SVGIconPanel[]{
            goPanel1,
            goPanel2,
            goPanel3,
            goPanel4,
            goPanel5,
            goPanel6
        };
    }
    
    protected RoundedButton[] getHyperlinkButtons(){
        
        return new RoundedButton[]{
          
            hyperlink1,
            hyperlink2,
            hyperlink3,
            hyperlink4,
            hyperlink5,
            hyperlink6
        };
    }
    
    
    public static hyperlinkViewFrame createInstance(SourceFrame sf, Term existingTerm){
        
        
        hyperlinkViewFrame hvf = new hyperlinkViewFrame(sf, existingTerm);
        hyperlinkViewController.initializeController(hvf, sf, existingTerm);
        return hvf;
    }
    
    public static hyperlinkViewFrame createInstanceWithoutController(SourceFrame sf, Term existingTerm){
        
        return new hyperlinkViewFrame(sf, existingTerm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hyperlinkLabel2 = new javax.swing.JLabel();
        hyperlinkPanel2 = new frontend.RoundedPanel();
        hyperlinkLabel1 = new javax.swing.JLabel();
        hyperlinkLabel3 = new javax.swing.JLabel();
        hyperlinkPanel3 = new frontend.RoundedPanel();
        hyperlinkPanel1 = new frontend.RoundedPanel();
        hyperlinkLabel4 = new javax.swing.JLabel();
        hyperlinkPanel4 = new frontend.RoundedPanel();
        hyperlinkPanel6 = new frontend.RoundedPanel();
        hyperlinkLabel6 = new javax.swing.JLabel();
        hyperlinkPanel5 = new frontend.RoundedPanel();
        hyperlinkLabel5 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        goPanel1 = new frontend.SVGIconPanel();
        goPanel2 = new frontend.SVGIconPanel();
        goPanel3 = new frontend.SVGIconPanel();
        goPanel4 = new frontend.SVGIconPanel();
        goPanel5 = new frontend.SVGIconPanel();
        goPanel6 = new frontend.SVGIconPanel();
        hyperlink4 = new frontend.RoundedButton();
        hyperlink1 = new frontend.RoundedButton();
        hyperlink2 = new frontend.RoundedButton();
        hyperlink6 = new frontend.RoundedButton();
        hyperlink3 = new frontend.RoundedButton();
        hyperlink5 = new frontend.RoundedButton();

        hyperlinkLabel2.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel2.setText("jLabel1");

        hyperlinkPanel2.setArcSize(20);
        hyperlinkPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkLabel1.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel1.setText("jLabel1");

        hyperlinkLabel3.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel3.setText("jLabel1");

        hyperlinkPanel3.setArcSize(20);
        hyperlinkPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkPanel1.setArcSize(20);
        hyperlinkPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkLabel4.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel4.setText("jLabel1");

        hyperlinkPanel4.setArcSize(20);
        hyperlinkPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkPanel6.setArcSize(20);
        hyperlinkPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkLabel6.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel6.setText("jLabel1");
        hyperlinkPanel6.add(hyperlinkLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 50));

        hyperlinkPanel5.setArcSize(20);
        hyperlinkPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkLabel5.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkLabel5.setText("jLabel1");
        hyperlinkPanel5.add(hyperlinkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(590, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(44, 62, 80));
        parentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Browse Hyperlinks");
        parentPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, -1));

        try {
            goPanel1.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel1.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel1.setIconSquarePadding(0.5);
        parentPanel.add(goPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        try {
            goPanel2.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel2.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel2.setIconSquarePadding(0.5);
        parentPanel.add(goPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        try {
            goPanel3.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel3.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel3.setIconSquarePadding(0.5);
        parentPanel.add(goPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        try {
            goPanel4.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel4.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel4.setIconSquarePadding(0.5);
        parentPanel.add(goPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        try {
            goPanel5.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel5.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel5.setIconSquarePadding(0.5);
        parentPanel.add(goPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        try {
            goPanel6.set_SVG_URL_String("/images/icons/right-circle-white.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        goPanel6.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        goPanel6.setIconSquarePadding(0.5);
        parentPanel.add(goPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        hyperlink4.setArcSize(20);
        hyperlink4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 530, -1));

        hyperlink1.setArcSize(20);
        hyperlink1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 530, -1));

        hyperlink2.setArcSize(20);
        hyperlink2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 530, -1));

        hyperlink6.setArcSize(20);
        hyperlink6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 530, -1));

        hyperlink3.setArcSize(20);
        hyperlink3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 530, -1));

        hyperlink5.setArcSize(20);
        hyperlink5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentPanel.add(hyperlink5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 530, -1));

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.SVGIconPanel goPanel1;
    private frontend.SVGIconPanel goPanel2;
    private frontend.SVGIconPanel goPanel3;
    private frontend.SVGIconPanel goPanel4;
    private frontend.SVGIconPanel goPanel5;
    private frontend.SVGIconPanel goPanel6;
    private frontend.RoundedButton hyperlink1;
    private frontend.RoundedButton hyperlink2;
    private frontend.RoundedButton hyperlink3;
    private frontend.RoundedButton hyperlink4;
    private frontend.RoundedButton hyperlink5;
    private frontend.RoundedButton hyperlink6;
    private javax.swing.JLabel hyperlinkLabel1;
    private javax.swing.JLabel hyperlinkLabel2;
    private javax.swing.JLabel hyperlinkLabel3;
    private javax.swing.JLabel hyperlinkLabel4;
    private javax.swing.JLabel hyperlinkLabel5;
    private javax.swing.JLabel hyperlinkLabel6;
    private frontend.RoundedPanel hyperlinkPanel1;
    private frontend.RoundedPanel hyperlinkPanel2;
    private frontend.RoundedPanel hyperlinkPanel3;
    private frontend.RoundedPanel hyperlinkPanel4;
    private frontend.RoundedPanel hyperlinkPanel5;
    private frontend.RoundedPanel hyperlinkPanel6;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
