/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Term;
import backend.TermDataManagement;
import book.bookpicker.Book;
import legacy.BehaviourForSwing;
import legacy.ButtonActionCode;
import legacy.TextBoxContentEventCode;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author BRIN
 */
public class hyperlinkEditFrame extends javax.swing.JFrame {
    
    private Book initialisedBook;
    private TermDataManagement tdm;
    private Term existingTerm;
    private Term newTerm;
    private boolean termFound;
    private referenceEditFrame ref;
    
    //FORMAL CONSTRUCTOR::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    public hyperlinkEditFrame(Book initialisedBook, TermDataManagement tdm, Term existingTerm, Term newTerm, boolean  termFound, referenceEditFrame ref) {
        
        this.initialisedBook = initialisedBook;
        this.tdm = tdm;
        this.existingTerm = existingTerm;
        this.newTerm = newTerm;
        this.termFound = termFound;
        this.ref = ref;
        initComponents();
        hyperlinkEditFrameGUIBehaviour hyperlinkEditFrameGUIBehaviour = new hyperlinkEditFrameGUIBehaviour(this);
    }
    
    public Book getInitialisedBook(){
        
        return this.initialisedBook;
    }
    
    public TermDataManagement getTDM(){
        
        return this.tdm;
    }
    
    public Term getExistingTerm(){
        
        return this.existingTerm;
    }
    
    public Term getNewTerm(){
        
        return this.newTerm;
    }
    
    public boolean getTermFound(){
        
        return this.termFound;
    }
    
    public referenceEditFrame getREFParent(){
        
        return this.ref;
    }
            
    
    public JTextField[] getHyperlinkBoxes(){
        
        return new JTextField[]{
            
            hyperlinkBox1,
            hyperlinkBox2,
            hyperlinkBox3,
            hyperlinkBox4,
            hyperlinkBox5,
            hyperlinkBox6
        };
    }
    
    public JTextField[] getEncapBoxes(){
        
        return new JTextField[]{
            
            encapBox1,
            encapBox2,
            encapBox3,
            encapBox4,
            encapBox5,
            encapBox6
        };
    }
    
    public RoundedButton[] getAdjacentButtons(){
        
        return new RoundedButton[]{
            
            adjacentButton1,
            adjacentButton2,
            adjacentButton3,
            adjacentButton4,
            adjacentButton5,
            adjacentButton6
        };
    }
    
    public RoundedButton getBackButton(){
        
        return backButton;
    }
    
    public RoundedButton getSaveButton(){
        
        return saveButton;
    }
    
    public RoundedButton getSaveAndSkipButton(){
        
        return skipSaveButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adjacentButton6 = new frontend.RoundedButton();
        adjacentButton5 = new frontend.RoundedButton();
        adjacentButton4 = new frontend.RoundedButton();
        adjacentButton3 = new frontend.RoundedButton();
        adjacentButton2 = new frontend.RoundedButton();
        adjacentButton1 = new frontend.RoundedButton();
        containerPanel = new javax.swing.JPanel();
        hyperlinkBox1 = new javax.swing.JTextField();
        encapBox1 = new javax.swing.JTextField();
        encapBox2 = new javax.swing.JTextField();
        hyperlinkBox2 = new javax.swing.JTextField();
        encapBox3 = new javax.swing.JTextField();
        hyperlinkBox3 = new javax.swing.JTextField();
        encapBox4 = new javax.swing.JTextField();
        hyperlinkBox4 = new javax.swing.JTextField();
        encapBox5 = new javax.swing.JTextField();
        hyperlinkBox5 = new javax.swing.JTextField();
        encapBox6 = new javax.swing.JTextField();
        hyperlinkBox6 = new javax.swing.JTextField();
        sep5 = new javax.swing.JSeparator();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        sep4 = new javax.swing.JSeparator();
        decorativePanel = new frontend.RoundedPanel();
        headerLabel = new javax.swing.JLabel();
        backButton = new frontend.RoundedButton();
        statusLabel = new javax.swing.JLabel();
        saveButton = new frontend.RoundedButton();
        skipSaveButton = new frontend.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit hyperlinks for: '" + newTerm.getAbsoluteSpelling() + "'");
        setMinimumSize(new java.awt.Dimension(590, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(590, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(44, 62, 80));
        parentPanel.setMaximumSize(new java.awt.Dimension(590, 720));
        parentPanel.setMinimumSize(new java.awt.Dimension(590, 720));
        parentPanel.setPreferredSize(new java.awt.Dimension(590, 720));
        parentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Edit Hyperlinks");
        parentPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        parentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 209, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        parentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 299, 40, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("4");
        parentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 389, 40, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("5");
        parentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 479, 40, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("6");
        parentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 569, 40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1");
        parentPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 119, 40, 40));

        adjacentButton6.setText("");
        adjacentButton6.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton6.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        parentPanel.add(adjacentButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 570, 40, 40));
        adjacentButton6.getAccessibleContext().setAccessibleName("adjacentButton6");

        adjacentButton5.setText("");
        adjacentButton5.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton5.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        parentPanel.add(adjacentButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 480, 40, 40));
        adjacentButton5.getAccessibleContext().setAccessibleName("adjacentButton5");

        adjacentButton4.setText("");
        adjacentButton4.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton4.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        parentPanel.add(adjacentButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 390, 40, 40));
        adjacentButton4.getAccessibleContext().setAccessibleName("adjacentButton4");

        adjacentButton3.setText("");
        adjacentButton3.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton3.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        parentPanel.add(adjacentButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 300, 40, 40));
        adjacentButton3.getAccessibleContext().setAccessibleName("adjacentButton3");

        adjacentButton2.setText("");
        adjacentButton2.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton2.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        parentPanel.add(adjacentButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 210, 40, 40));
        adjacentButton2.getAccessibleContext().setAccessibleName("adjacentButton2");

        adjacentButton1.setText("");
        adjacentButton1.setDefaultColor(new java.awt.Color(27, 36, 45));
        adjacentButton1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        adjacentButton1.setIconTextGap(0);
        parentPanel.add(adjacentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 40, 40));
        adjacentButton1.getAccessibleContext().setAccessibleName("adjacentButton1");

        containerPanel.setOpaque(false);
        containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hyperlinkBox1.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox1.setForeground(new java.awt.Color(204, 204, 204));
        hyperlinkBox1.setText("<Links to...>");
        hyperlinkBox1.setBorder(null);
        hyperlinkBox1.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, -1));

        encapBox1.setBackground(new java.awt.Color(57, 75, 92));
        encapBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox1.setForeground(new java.awt.Color(153, 153, 153));
        encapBox1.setText("<Enter Encapsulating Text>");
        encapBox1.setBorder(null);
        encapBox1.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, -1));

        encapBox2.setBackground(new java.awt.Color(57, 75, 92));
        encapBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox2.setForeground(new java.awt.Color(255, 255, 255));
        encapBox2.setText("<Enter Encapsulating Text>");
        encapBox2.setBorder(null);
        encapBox2.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 490, -1));

        hyperlinkBox2.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox2.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkBox2.setText("<Links to...>");
        hyperlinkBox2.setBorder(null);
        hyperlinkBox2.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 490, -1));

        encapBox3.setBackground(new java.awt.Color(57, 75, 92));
        encapBox3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox3.setForeground(new java.awt.Color(255, 255, 255));
        encapBox3.setText("<Enter Encapsulating Text>");
        encapBox3.setBorder(null);
        encapBox3.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 490, -1));

        hyperlinkBox3.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox3.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkBox3.setText("<Links to...>");
        hyperlinkBox3.setBorder(null);
        hyperlinkBox3.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 490, -1));

        encapBox4.setBackground(new java.awt.Color(57, 75, 92));
        encapBox4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox4.setForeground(new java.awt.Color(255, 255, 255));
        encapBox4.setText("<Enter Encapsulating Text>");
        encapBox4.setBorder(null);
        encapBox4.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 490, -1));

        hyperlinkBox4.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox4.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkBox4.setText("<Links to...>");
        hyperlinkBox4.setBorder(null);
        hyperlinkBox4.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 490, -1));

        encapBox5.setBackground(new java.awt.Color(57, 75, 92));
        encapBox5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox5.setForeground(new java.awt.Color(255, 255, 255));
        encapBox5.setText("<Enter Encapsulating Text>");
        encapBox5.setBorder(null);
        encapBox5.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 490, -1));

        hyperlinkBox5.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox5.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkBox5.setText("<Links to...>");
        hyperlinkBox5.setBorder(null);
        hyperlinkBox5.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 490, -1));

        encapBox6.setBackground(new java.awt.Color(57, 75, 92));
        encapBox6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encapBox6.setForeground(new java.awt.Color(255, 255, 255));
        encapBox6.setText("<Enter Encapsulating Text>");
        encapBox6.setBorder(null);
        encapBox6.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(encapBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 490, -1));

        hyperlinkBox6.setBackground(new java.awt.Color(57, 75, 92));
        hyperlinkBox6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hyperlinkBox6.setForeground(new java.awt.Color(255, 255, 255));
        hyperlinkBox6.setText("<Links to...>");
        hyperlinkBox6.setBorder(null);
        hyperlinkBox6.setCaretColor(new java.awt.Color(255, 255, 255));
        containerPanel.add(hyperlinkBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 490, -1));
        containerPanel.add(sep5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 490, 10));
        containerPanel.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 10));
        containerPanel.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 490, 10));
        containerPanel.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 490, 10));
        containerPanel.add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 490, 10));

        parentPanel.add(containerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 530, 530));

        decorativePanel.setDefaultColor(new java.awt.Color(57, 75, 92));

        javax.swing.GroupLayout decorativePanelLayout = new javax.swing.GroupLayout(decorativePanel);
        decorativePanel.setLayout(decorativePanelLayout);
        decorativePanelLayout.setHorizontalGroup(
            decorativePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        decorativePanelLayout.setVerticalGroup(
            decorativePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        parentPanel.add(decorativePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 530, 530));

        headerLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Hyperlinks:");
        parentPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        backButton.setText("Back");
        backButton.setDefaultColor(new java.awt.Color(27, 36, 45));
        parentPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, -1));

        statusLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        parentPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 410, 20));

        saveButton.setText("Save");
        saveButton.setDefaultColor(new java.awt.Color(27, 36, 45));
        parentPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, -1));

        skipSaveButton.setText("Skip and Save");
        skipSaveButton.setDefaultColor(new java.awt.Color(27, 36, 45));
        parentPanel.add(skipSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.RoundedButton adjacentButton1;
    private frontend.RoundedButton adjacentButton2;
    private frontend.RoundedButton adjacentButton3;
    private frontend.RoundedButton adjacentButton4;
    private frontend.RoundedButton adjacentButton5;
    private frontend.RoundedButton adjacentButton6;
    private frontend.RoundedButton backButton;
    private javax.swing.JPanel containerPanel;
    private frontend.RoundedPanel decorativePanel;
    private javax.swing.JTextField encapBox1;
    private javax.swing.JTextField encapBox2;
    private javax.swing.JTextField encapBox3;
    private javax.swing.JTextField encapBox4;
    private javax.swing.JTextField encapBox5;
    private javax.swing.JTextField encapBox6;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField hyperlinkBox1;
    private javax.swing.JTextField hyperlinkBox2;
    private javax.swing.JTextField hyperlinkBox3;
    private javax.swing.JTextField hyperlinkBox4;
    private javax.swing.JTextField hyperlinkBox5;
    private javax.swing.JTextField hyperlinkBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel parentPanel;
    private frontend.RoundedButton saveButton;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JSeparator sep5;
    private frontend.RoundedButton skipSaveButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
