/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Term;
import backend.TermDataManagement;
import book.bookpicker.Book;
import com.quartzwater.medicalglossary.BehaviourForSwing;
import com.quartzwater.medicalglossary.ButtonActionCode;
import com.quartzwater.medicalglossary.TextBoxContentEventCode;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

/**
 *
 * @author BRIN
 */
public class referenceEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form definitionEditFrame
     */
    
    private Book initialisedBook;
    private TermDataManagement tdm;
    private Term existingTerm;
    private Term newTerm;
    private boolean termFound;
    
    private definitionEditFrame parentFrame;
    
    public referenceEditFrame(Book initialisedBook, TermDataManagement tdm, Term existingTerm, Term newTerm, boolean  termFound, definitionEditFrame def) {
        
        
        this.initialisedBook = initialisedBook;
        this.tdm = tdm;
        this.existingTerm = existingTerm;
        this.newTerm = newTerm;
        this.termFound = termFound;
        this.parentFrame = def;
        
        initComponents();
        
        new referenceEditFrameGUIBehaviour(this);
    }
    
    public Book getInitialisedBook(){
        
        return initialisedBook;
    }
    
    public TermDataManagement getTDM(){
        
        return tdm;
    }
    
    public Term getExistingTerm(){
        
        return existingTerm;
    }
    
    public Term getNewTerm(){
        
        return newTerm;
    }
    
    public boolean getTermFound(){
        
        return termFound;
    }
    
    public definitionEditFrame getDEFParent(){
        
        return parentFrame;
    }
    
    public JTextField getPageBox(){
        
        return pageBox;
    }
    
    public JLabel getBookField(){
        
        return bookTextBox;
    }
    
    public JLabel getChapterField(){
        
        return chapterTextBox;
    }
    
    public JLabel getMajorTopicField(){
        
        return majorTopicTextBox;
    }
    
    public JTextArea getSubtopicField(){
        
        return subtopicTextArea;
    }
    
    public RoundedButton getBackButton(){
        
        return backButton;
    }
    
    public RoundedButton getNextButton(){
        
        return nextButton;
    }
    
    public JLabel getStatusLabel(){
        
        return statusLabel;
    }
    
    public JLabel getHeaderLabel(){
        
        return headerLabel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        pageBox = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        statusTextArea = new javax.swing.JTextArea();
        containerPanel = new javax.swing.JPanel();
        subtopicTextArea = new javax.swing.JTextArea();
        chapterTextBox = new javax.swing.JLabel();
        chapterLabel = new javax.swing.JLabel();
        majorTopicLabel = new javax.swing.JLabel();
        majorTopicTextBox = new javax.swing.JLabel();
        subtopicLabel = new javax.swing.JLabel();
        bookLabel = new javax.swing.JLabel();
        bookTextBox = new javax.swing.JLabel();
        decorativePanel = new frontend.RoundedPanel();
        headerLabel = new javax.swing.JLabel();
        backButton = new frontend.RoundedButton();
        statusLabel = new javax.swing.JLabel();
        nextButton = new frontend.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Reference for: '" + newTerm.getAbsoluteSpelling() + "'");
        setMinimumSize(new java.awt.Dimension(590, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(590, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(44, 62, 80));
        parentPanel.setMaximumSize(new java.awt.Dimension(590, 720));
        parentPanel.setMinimumSize(new java.awt.Dimension(590, 720));
        parentPanel.setPreferredSize(new java.awt.Dimension(590, 720));
        parentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageBox.setBackground(new java.awt.Color(68, 96, 122));
        pageBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageBox.setForeground(new java.awt.Color(255, 255, 255));
        pageBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pageBox.setText("<Page Number>");
        pageBox.setCaretColor(new java.awt.Color(255, 255, 255));
        pageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageBoxActionPerformed(evt);
            }
        });
        parentPanel.add(pageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 470, 40));

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Edit Reference");
        parentPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, -1));

        statusTextArea.setColumns(20);
        statusTextArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusTextArea.setForeground(new java.awt.Color(255, 255, 255));
        statusTextArea.setLineWrap(true);
        statusTextArea.setRows(5);
        statusTextArea.setWrapStyleWord(true);
        statusTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        statusTextArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        statusTextArea.setOpaque(false);
        parentPanel.add(statusTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 200, 70));

        containerPanel.setOpaque(false);
        containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtopicTextArea.setEditable(false);
        subtopicTextArea.setColumns(20);
        subtopicTextArea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subtopicTextArea.setForeground(new java.awt.Color(255, 255, 255));
        subtopicTextArea.setLineWrap(true);
        subtopicTextArea.setRows(5);
        subtopicTextArea.setText(" -");
        subtopicTextArea.setWrapStyleWord(true);
        subtopicTextArea.setBorder(null);
        subtopicTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        subtopicTextArea.setFocusable(false);
        subtopicTextArea.setOpaque(false);
        subtopicTextArea.setPreferredSize(new java.awt.Dimension(450, 160));
        containerPanel.add(subtopicTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 490, 140));

        chapterTextBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        chapterTextBox.setForeground(new java.awt.Color(255, 255, 255));
        chapterTextBox.setText(" -");
        containerPanel.add(chapterTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 490, -1));

        chapterLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chapterLabel.setForeground(new java.awt.Color(204, 204, 204));
        chapterLabel.setText(" Chapter:");
        containerPanel.add(chapterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        majorTopicLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        majorTopicLabel.setForeground(new java.awt.Color(204, 204, 204));
        majorTopicLabel.setText(" Major Topic:");
        containerPanel.add(majorTopicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        majorTopicTextBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        majorTopicTextBox.setForeground(new java.awt.Color(255, 255, 255));
        majorTopicTextBox.setText(" -");
        containerPanel.add(majorTopicTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 490, -1));

        subtopicLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subtopicLabel.setForeground(new java.awt.Color(204, 204, 204));
        subtopicLabel.setText(" Subtopic:");
        containerPanel.add(subtopicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, -1));

        bookLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookLabel.setForeground(new java.awt.Color(204, 204, 204));
        bookLabel.setText(" Book:");
        containerPanel.add(bookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        bookTextBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookTextBox.setForeground(new java.awt.Color(255, 255, 255));
        bookTextBox.setText(" -");
        containerPanel.add(bookTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, -1));

        parentPanel.add(containerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 530, 410));

        decorativePanel.setDefaultColor(new java.awt.Color(57, 75, 92));

        javax.swing.GroupLayout decorativePanelLayout = new javax.swing.GroupLayout(decorativePanel);
        decorativePanel.setLayout(decorativePanelLayout);
        decorativePanelLayout.setHorizontalGroup(
            decorativePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        decorativePanelLayout.setVerticalGroup(
            decorativePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        parentPanel.add(decorativePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 530, 410));

        headerLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Reference:");
        parentPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));

        backButton.setText("Back");
        backButton.setDefaultColor(new java.awt.Color(255, 51, 51));
        parentPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        statusLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Use up/down keys to cycle through various entries ()");
        parentPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 470, 20));

        nextButton.setText("Next");
        parentPanel.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, -1));

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pageBoxActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.RoundedButton backButton;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JLabel bookTextBox;
    private javax.swing.JLabel chapterLabel;
    private javax.swing.JLabel chapterTextBox;
    private javax.swing.JPanel containerPanel;
    private frontend.RoundedPanel decorativePanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel majorTopicLabel;
    private javax.swing.JLabel majorTopicTextBox;
    private frontend.RoundedButton nextButton;
    private javax.swing.JTextField pageBox;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextArea statusTextArea;
    private javax.swing.JLabel subtopicLabel;
    private javax.swing.JTextArea subtopicTextArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
