/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend;

import backend.AppConstants;
import backend.SVGIconRenderer;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.swing.Action;
import javax.swing.ImageIcon;

/**
 *
 * @author BRIN
 */
public class SaveSuccessful extends javax.swing.JDialog {

    /**
     * Creates new form SaveSuccessful
     */
    public SaveSuccessful(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        okButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getDefaultColor());
        
        if(parent instanceof hyperlinkEditFrame hef){
            String previous = headerLabel.getText();
            if(hef.getTermFound()){
                
                headerLabel.setText(previous.replace("%", "Updated!"));
            }
            else{
                
                headerLabel.setText(previous.replace("%", "Created!"));
            }
        
        
        MouseAdapter okMAdapt = new MouseAdapter() {
            
            @Override
            public void mouseEntered(MouseEvent event){
                okButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
            }
            
            @Override
            public void mouseExited(MouseEvent event){
                okButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getDefaultColor());
            }
            
            @Override
            public void mousePressed(MouseEvent event){
                okButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getPressedColor());
            }
            
            @Override
            public void mouseReleased(MouseEvent event){
                okButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
            }
        };
        
        ActionListener okActListen = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                hef.getREFParent().getDEFParent().getSFParent().getSpellingBox().setText(hef.getNewTerm().getSpelling());
                getMyself().dispose();
                hef.dispose();
            }
        };
        
        okButton.addMouseListener(okMAdapt);
        okButton.addActionListener(okActListen);
        
        }
    }
    
    private SaveSuccessful getMyself(){
        
        return this;
    }
    private static Image getScaledImage(Image srcImg, int w, int h) {
        // Create a new buffered image with the desired dimensions
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        // Set rendering hints for high-quality scaling
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Draw the original image onto the new buffered image
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();

        return resizedImg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        sVGIconPanel2 = new frontend.SVGIconPanel();
        okButton = new frontend.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saved");
        setResizable(false);
        setSize(new java.awt.Dimension(530, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Term Successfully %");
        jPanel1.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 470, -1));

        sVGIconPanel2.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);

        javax.swing.GroupLayout sVGIconPanel2Layout = new javax.swing.GroupLayout(sVGIconPanel2);
        sVGIconPanel2.setLayout(sVGIconPanel2Layout);
        sVGIconPanel2Layout.setHorizontalGroup(
            sVGIconPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        sVGIconPanel2Layout.setVerticalGroup(
            sVGIconPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(sVGIconPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 60));

        okButton.setText("Okay!");
        okButton.setArcSize(35);
        okButton.setDefaultColor(new java.awt.Color(43, 181, 114));
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveSuccessful dialog = new SaveSuccessful(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private frontend.RoundedButton okButton;
    private frontend.SVGIconPanel sVGIconPanel2;
    // End of variables declaration//GEN-END:variables
}
