/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AppConfig;
import java.util.Properties;
import javax.swing.JLabel;

/**
 *
 * @author BRIN
 */
public class SettingsFrame extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SettingsFrame.class.getName());

    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame(javax.swing.JFrame parent) {
        super(parent, true);
        initComponents();
    }
    
    public static SettingsFrame generateInstance(javax.swing.JFrame parent){
        SettingsFrame settings = new SettingsFrame(parent);
        SettingsFrameController.initializeController(settings);
        return settings;
    }
    
    public static SettingsFrame generateInstance(javax.swing.JFrame parent, boolean initialize){
        SettingsFrame settings = new SettingsFrame(parent);
        if(initialize){
            SettingsFrameController.initializeController(settings);
        }
        
        return settings;
    }
    
    protected RoundedButton getStorageLocation(){
        return this.storageText;
    }
    
    protected  RoundedButton getChangeButton(){
        return this.changeButton;
    }
    
    protected RoundedButton getDeepButton(){
        return this.deepDepthButton;
    }
    
    protected RoundedButton getBalancedButton(){
        return this.balancedDepthButton;
    }
    
    protected RoundedButton getShallowButton(){
        return this.shallowDepthButton;
    }
    
    protected RoundedButton getSaveButton(){
        return this.saveButton;
    }
    
    protected RoundedButton getCancelButton(){
        return this.cancelButton;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        decorativePanel = new frontend.RoundedPanel();
        DefaultSearchDepthHeeader = new javax.swing.JLabel();
        defaultSaveHeader = new javax.swing.JLabel();
        shallowDepthButton = new frontend.RoundedButton();
        deepDepthButton = new frontend.RoundedButton();
        balancedDepthButton = new frontend.RoundedButton();
        folderIcon = new frontend.SVGIconPanel();
        storageText = new frontend.RoundedButton();
        changeButton = new frontend.RoundedButton();
        cancelButton = new frontend.RoundedButton();
        statusLabel = new javax.swing.JLabel();
        saveButton = new frontend.RoundedButton();
        settingsIconPanel = new frontend.SVGIconPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);
        setSize(new java.awt.Dimension(590, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(44, 62, 80));
        parentPanel.setMaximumSize(new java.awt.Dimension(590, 720));
        parentPanel.setMinimumSize(new java.awt.Dimension(590, 720));
        parentPanel.setPreferredSize(new java.awt.Dimension(590, 720));
        parentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Settings");
        parentPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, 40));

        decorativePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DefaultSearchDepthHeeader.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        DefaultSearchDepthHeeader.setForeground(new java.awt.Color(255, 255, 255));
        DefaultSearchDepthHeeader.setText("Search Depth:");
        decorativePanel.add(DefaultSearchDepthHeeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, -1));

        defaultSaveHeader.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        defaultSaveHeader.setForeground(new java.awt.Color(255, 255, 255));
        defaultSaveHeader.setText("Term Storage Location:");
        decorativePanel.add(defaultSaveHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, -1));

        shallowDepthButton.setForeground(new java.awt.Color(102, 102, 102));
        shallowDepthButton.setText("Shallow");
        shallowDepthButton.setArcSize(15);
        shallowDepthButton.setCurrentColor(new java.awt.Color(255, 255, 255));
        decorativePanel.add(shallowDepthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 150, 30));

        deepDepthButton.setForeground(new java.awt.Color(102, 102, 102));
        deepDepthButton.setText("Deep");
        deepDepthButton.setArcSize(15);
        deepDepthButton.setCurrentColor(new java.awt.Color(255, 255, 255));
        decorativePanel.add(deepDepthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        balancedDepthButton.setForeground(new java.awt.Color(102, 102, 102));
        balancedDepthButton.setText("Balanced");
        balancedDepthButton.setArcSize(15);
        balancedDepthButton.setCurrentColor(new java.awt.Color(255, 255, 255));
        decorativePanel.add(balancedDepthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

        try {
            folderIcon.set_SVG_URL_String("/images/icons/folder.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        folderIcon.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        folderIcon.setIconSquarePadding(10.0);
        decorativePanel.add(folderIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 40, 40));

        storageText.setText("Change ");
        storageText.setArcSize(20);
        storageText.setCurrentColor(new java.awt.Color(44, 62, 80));
        storageText.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        storageText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        storageText.setInheritsPopupMenu(true);
        decorativePanel.add(storageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 490, 40));

        changeButton.setText("Change ");
        changeButton.setArcSize(20);
        changeButton.setCurrentColor(new java.awt.Color(44, 62, 80));
        changeButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        changeButton.setInheritsPopupMenu(true);
        decorativePanel.add(changeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 120, -1));

        parentPanel.add(decorativePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 530, 550));

        cancelButton.setText("Cancel");
        cancelButton.setCurrentColor(new java.awt.Color(27, 36, 45));
        parentPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 130, 40));

        statusLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parentPanel.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 470, 20));

        saveButton.setText("Save");
        saveButton.setCurrentColor(new java.awt.Color(27, 36, 45));
        parentPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 130, 40));

        try {
            settingsIconPanel.set_SVG_URL_String("/images/icons/settings.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        settingsIconPanel.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        settingsIconPanel.setIconSquarePadding(5.0);
        parentPanel.add(settingsIconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, 110));

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        AppConfig.resetUserProperties();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DefaultSearchDepthHeeader;
    private frontend.RoundedButton balancedDepthButton;
    private frontend.RoundedButton cancelButton;
    private frontend.RoundedButton changeButton;
    private frontend.RoundedPanel decorativePanel;
    private frontend.RoundedButton deepDepthButton;
    private javax.swing.JLabel defaultSaveHeader;
    private frontend.SVGIconPanel folderIcon;
    private javax.swing.JPanel parentPanel;
    private frontend.RoundedButton saveButton;
    private frontend.SVGIconPanel settingsIconPanel;
    private frontend.RoundedButton shallowDepthButton;
    private javax.swing.JLabel statusLabel;
    private frontend.RoundedButton storageText;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
