/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend.v2.window;

import backend.AppConstants;
import backend.eventadapter.GranularMouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

/**
 *
 * @author BRIN
 */
public class ContentEditWarning extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContentEditWarning.class.getName());

    public enum Response {
        YES,
        NO,
        ESCAPE
    }
    
    private Response currentResponse = Response.ESCAPE;
    
    /**
     * Creates new form ContentEditWarning
     */
    public ContentEditWarning() {
        super((JFrame) null, true);
        initComponents();
        noButton.addMouseListener(NOGran);
        yesButton.addMouseListener(YESGran);
        invalid.setVisible(false);
    }
    
    public static Response showDialog(){
        ContentEditWarning contentEditWarning = new ContentEditWarning();
        contentEditWarning.setVisible(true);
        return contentEditWarning.currentResponse;
    }
    
    public static Response showDialogWithInvalid(){
        ContentEditWarning contentEditWarning = new ContentEditWarning();
        contentEditWarning.invalid.setVisible(true);
        contentEditWarning.yesButton.setEnabled(false);
        contentEditWarning.setVisible(true);
        
        return contentEditWarning.currentResponse;
    }
    
    private GranularMouseAdapter YESGran = new GranularMouseAdapter(){
            
        @Override
        public void actOnMouseEntry(MouseEvent e){
            yesButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
        }
        
        @Override
        public void actOnMouseExit(MouseEvent e){
            yesButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getDefaultColor());
        }
        
        @Override
        public void actOnMousePress(MouseEvent e){
            yesButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getPressedColor());
        }
        
        @Override
        public void actOnMouseRelease(MouseEvent e){
            yesButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
            currentResponse = Response.YES;
            dispose();
        }
    };
    
    private GranularMouseAdapter NOGran = new GranularMouseAdapter(){
            
        @Override
        public void actOnMouseEntry(MouseEvent e){
            noButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getHoverColor());
        }
        
        @Override
        public void actOnMouseExit(MouseEvent e){
            noButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getDefaultColor());
        }
        
        @Override
        public void actOnMousePress(MouseEvent e){
            noButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getPressedColor());
        }
        
        @Override
        public void actOnMouseRelease(MouseEvent e){
            noButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getHoverColor());
            currentResponse = Response.NO;
            dispose();
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        roundedPanel1 = new frontend.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        invalid = new javax.swing.JLabel();
        yesButton = new frontend.RoundedButton();
        noButton = new frontend.RoundedButton();
        sVGIconPanel1 = new frontend.SVGIconPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Would you like to save changes?");

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("No");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(460, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 52, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Changes Detected");
        roundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 400, 50));

        jPanel2.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 60));

        invalid.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        invalid.setForeground(new java.awt.Color(255, 102, 102));
        invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invalid.setText("Invalid state detected");
        jPanel2.add(invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 400, 40));

        yesButton.setText("YES");
        yesButton.setArcSize(15);
        yesButton.setCurrentColor(new java.awt.Color(15, 20, 25));
        jPanel2.add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        noButton.setText("NO");
        noButton.setArcSize(15);
        noButton.setCurrentColor(new java.awt.Color(15, 20, 25));
        jPanel2.add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, -1));

        try {
            sVGIconPanel1.set_SVG_URL_String("/icons/alert/question-mark.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        sVGIconPanel1.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        jPanel2.add(sVGIconPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 18, 160, 60));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Would you like to save the changes made?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 400, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invalid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private frontend.RoundedButton noButton;
    private frontend.RoundedPanel roundedPanel1;
    private frontend.SVGIconPanel sVGIconPanel1;
    private frontend.RoundedButton yesButton;
    // End of variables declaration//GEN-END:variables
}
