/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend.v2.window;

import backend.AppConfig;
import java.awt.Color;

/**
 *
 * @author BRIN
 */
public class Startup extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Startup.class.getName());

    /**
     * Creates new form Startup
     */
    public Startup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        versionLabel.setText("");
        this.setBackground(new Color(0,0,0,0));
        
        backDecorative.definePositionsForLGP(0, 0, 0, backDecorative.getPreferredSize().height);
        float[] fractions = {0.0f, 0.5f, 1.0f};
        Color[] colors = {
            new Color(0x2C, 0x53, 0x64),  // top: deep cyan-slate
            new Color(0x20, 0x3A, 0x43),  // middle: dark blue-gray
            new Color(0x0F, 0x20, 0x27)   // bottom: near black
        };

        backDecorative.enableLinearGradientPaint(fractions, colors);
    }
    
    public void setVersion(String text){
        this.versionLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backDecorative = new frontend.RoundedPanel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new frontend.RoundedPanel();
        authorLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        logoPanel = new frontend.SVGIconPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backDecorative.setArcSize(20);
        backDecorative.setPreferredSize(new java.awt.Dimension(400, 200));
        backDecorative.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 75, 92));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setArcSize(20);
        roundedPanel1.setCurrentColor(new java.awt.Color(15, 20, 25));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        authorLabel.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel.setText("BY: QuartzWater");
        roundedPanel1.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 380, -1));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 70));

        titleLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("MEDICAL GLOSSARY");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, -1));

        versionLabel.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setText("v0.5.0");
        jPanel1.add(versionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, -1));

        try {
            logoPanel.set_SVG_URL_String("/icons/main/title.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jPanel1.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 70));

        backDecorative.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 200));

        getContentPane().add(backDecorative, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private frontend.RoundedPanel backDecorative;
    private javax.swing.JPanel jPanel1;
    private frontend.SVGIconPanel logoPanel;
    private frontend.RoundedPanel roundedPanel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
