/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend.v2.window;

import backend.AppConstants;
import backend.eventadapter.GranularMouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author BRIN
 */
public class StateChangeWarning extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StateChangeWarning.class.getName());

    private boolean approved = false;
    /**
     * Creates new form StateChangeWarning
     */
    private StateChangeWarning(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cancelButton.addMouseListener(cancelBtnGran);
        continueButton.addMouseListener(continueBtnGran);
    }
    
    
    public static boolean showWarningDialog(){
        StateChangeWarning stw = new StateChangeWarning(null, true);
        stw.setVisible(true);
        return stw.approved;
    }
    
    private GranularMouseAdapter continueBtnGran = new GranularMouseAdapter(){
            
        @Override
        public void actOnMouseEntry(MouseEvent e){
            continueButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
        }
        
        @Override
        public void actOnMouseExit(MouseEvent e){
            continueButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getDefaultColor());
        }
        
        @Override
        public void actOnMousePress(MouseEvent e){
            continueButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getPressedColor());
        }
        
        @Override
        public void actOnMouseRelease(MouseEvent e){
            continueButton.setCurrentColor(AppConstants.DEFAULT_NEXT_BUTTON_CS_1.getHoverColor());
            approved = true;
            dispose();
        }
    };
    
    private GranularMouseAdapter cancelBtnGran = new GranularMouseAdapter(){
            
        @Override
        public void actOnMouseEntry(MouseEvent e){
            cancelButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getHoverColor());
        }
        
        @Override
        public void actOnMouseExit(MouseEvent e){
            cancelButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getDefaultColor());
        }
        
        @Override
        public void actOnMousePress(MouseEvent e){
            cancelButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getPressedColor());
        }
        
        @Override
        public void actOnMouseRelease(MouseEvent e){
            cancelButton.setCurrentColor(AppConstants.DEFAULT_BACK_BUTTON_CS_1.getHoverColor());
            
            dispose();
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new frontend.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        continueButton = new frontend.RoundedButton();
        cancelButton = new frontend.RoundedButton();
        sVGIconPanel1 = new frontend.SVGIconPanel();
        jLabel4 = new javax.swing.JLabel();

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Any unsaved Changes will be lost");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Warning : Create -> Search");
        setMinimumSize(new java.awt.Dimension(460, 300));
        setSize(new java.awt.Dimension(460, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 52, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mode Change");
        roundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 400, 50));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 60));

        continueButton.setText("CONTINUE");
        continueButton.setArcSize(15);
        continueButton.setCurrentColor(new java.awt.Color(15, 20, 25));
        jPanel1.add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 120, -1));

        cancelButton.setText("CANCEL");
        cancelButton.setArcSize(15);
        cancelButton.setCurrentColor(new java.awt.Color(15, 20, 25));
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, -1));

        try {
            sVGIconPanel1.set_SVG_URL_String("/icons/alert/warning.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        sVGIconPanel1.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        jPanel1.add(sVGIconPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 160, 60));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Any unsaved changes will be lost");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                StateChangeWarning dialog = new StateChangeWarning(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.RoundedButton cancelButton;
    private frontend.RoundedButton continueButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private frontend.RoundedPanel roundedPanel1;
    private frontend.SVGIconPanel sVGIconPanel1;
    // End of variables declaration//GEN-END:variables
}
