/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package frontend.v2.specialcomponent;

import frontend.RoundedPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.MultipleGradientPaint;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;

/**
 *
 * @author BRIN
 */
public class QuickAccess extends JPopupMenu {

    /**
     * Creates new form QuickAccess
     */
    
    private QuickAccessPanel qp;
    
    public QuickAccess() {
        initComponents();
        Dimension d = new Dimension(300,100);
        qp = new QuickAccessPanel();
        setPreferredSize(qp.getPreferredSize());
        setBorder(BorderFactory.createEmptyBorder());
        add(new QuickAccessPanel());
    }
    
    public void updateSelection(String selection){
        qp.updateSelection(selection);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        

        double width = getWidth();
        double height = getHeight();

        // Draw the main button shape on top of the shadow
        g2d.setColor(getBackground());
        
        
        
        g2d.fill(new RoundRectangle2D.Double(0, 0, width, height, 15, 15));
        
        g2d.dispose();
        super.paintComponent(g2d); // Call the super method to draw the text
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(null);
        setPopupSize(new java.awt.Dimension(300, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
