/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.v2.specialcomponent;

import backend.eventadapter.GranularMouseAdapter;
import frontend.RoundedPanel;
import frontend.v2.state.AppState;
import frontend.v2.state.QuickAccessEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author BRIN
 */
public class QuickAccessPanel extends RoundedPanel {

    /**
     * Creates new form QuickAccessPanel
     */
    
    private String selection;
    public QuickAccessPanel() {
        initComponents();
        selection = "";
        search_create_icon.addMouseListener(search_create_gran);
    }
    
    public void updateSelection(String selection){
        this.selection = selection;
    }
    
    private GranularMouseAdapter search_create_gran = new GranularMouseAdapter(){
            
        @Override
        public void actOnMouseRelease(MouseEvent e){
            AppState.fireQuickAccessEvent(this, selection, QuickAccessEvent.TYPE.SEARCH);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_create_icon = new frontend.SVGIconPanel();
        search_create_name = new javax.swing.JLabel();

        setArcSize(15);
        setCurrentColor(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(190, 45));
        setPreferredSize(new java.awt.Dimension(190, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            search_create_icon.set_SVG_URL_String("/icons/search-27-36-45.svg");
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        search_create_icon.setIconPosition(frontend.SVGIconPanel.iconPosition.CENTER);
        add(search_create_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 35, 35));

        search_create_name.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        search_create_name.setForeground(new java.awt.Color(204, 204, 204));
        search_create_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search_create_name.setText("SEARCH");
        add(search_create_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 5, 120, 35));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.SVGIconPanel search_create_icon;
    private javax.swing.JLabel search_create_name;
    // End of variables declaration//GEN-END:variables
}
